name: integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup neovim
      uses: rhysd/action-setup-vim@v1
      with:
        version: nightly
        neovim: true

    - name: Setup lua
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "luajit-2.1.0-beta3"

    - name: Setup luarocks
      uses: leafo/gh-actions-luarock
      with:
        luarocksVersion: "3.11.1"

    - name: Setup tools
      shell: bash
      run: |
        luarocks install luacheck
        luarocks install vusted

    - name: Run tests
      shell: bash
      run: make integration
